[package]
name = "msquare"
version = "0.1.0"
authors = ["jkueb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
rayon = "1.3.0"
csv = "1.1.3"
clap = "2.33.0"
